apiVersion: v1
kind: ConfigMap
metadata:
  name: locustfile-config
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class UsuarioDeCarga(HttpUser):
        wait_time = between(1, 2.5)
        print('Inicio')

        @task
        def hacer_inferencia(self):
            payload = {
                "feature1": 5.3,
                "feature2": 2.1,
                "feature3": 0.8
            }
            response = self.client.post("/predict", json=payload)
            if response.status_code != 200:
                print("❌ Error en la inferencia:", response.text)
